package com.example.bankomat.entity.enums;

public enum Huquqlar {
    ADDPOST, EDITPOST, READPOST, DELETEPOST, DELETEMYPOST,
    ADDCOMMENT,ADDMYCOMMENT, EDITCOMMENT, READCOMMENT, DELETECOMMENT, DELETEMYCOMMENT,
    ADDROLL, EDITROOL, READROOL, DELETEROOL,
    ADDUSER, EDITUSER, READUSER, DELETEUSER
}
